AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'OpsAgent Controller - Debug Version 2 (Minimal with auto IAM)'

Parameters:
  Environment:
    Type: String
    Default: sandbox

  ExecutionMode:
    Type: String
    Default: DRY_RUN

  TeamsBotAppId:
    Type: String
    Default: ''

  AzureTenantId:
    Type: String
    Default: ''

  AwsAccountId:
    Type: String
    Default: ''

Conditions:
  HasCustomAwsAccountId: !Not [!Equals [!Ref AwsAccountId, '']]

Resources:
  # API Gateway
  OpsAgentApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  # Lambda Function - Let SAM create IAM role automatically
  OpsAgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'opsagent-debug-v2-${Environment}'
      CodeUri: ../src/
      Handler: main.lambda_handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 512
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - CloudWatchLambdaInsightsExecutionRolePolicy
      Events:
        HealthCheck:
          Type: Api
          Properties:
            RestApiId: !Ref OpsAgentApi
            Path: /health
            Method: GET
        ChatMessage:
          Type: Api
          Properties:
            RestApiId: !Ref OpsAgentApi
            Path: /chat
            Method: POST
      Environment:
        Variables:
          TEAMS_BOT_APP_ID: !Ref TeamsBotAppId
          AZURE_TENANT_ID: !Ref AzureTenantId
          AWS_ACCOUNT_ID: !If [HasCustomAwsAccountId, !Ref AwsAccountId, !Ref 'AWS::AccountId']
          EXECUTION_MODE: !Ref ExecutionMode
          ENVIRONMENT: !Ref Environment

Outputs:
  ApiGatewayUrl:
    Value: !Sub 'https://${OpsAgentApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
  HealthEndpointUrl:
    Value: !Sub 'https://${OpsAgentApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/health'
  ChatEndpointUrl:
    Value: !Sub 'https://${OpsAgentApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/chat'
